# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(a338d1a5-bb29-436b-991a-2f5d8faf8a61)'
    appType: 'webAppLinux'
    appName: 'PacifcTourApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'